[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x4457b0e9551bccc46c9a1cfcb20f737cdeb1224baea74f7e2a90a41e28ad7932'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]